version: '2'
services:
  web:
    build: .
    volumes:
      - .:/docker-test
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    env_file:
      - .docker-test.env
